@if(auth()->user()->isCourier())
    @include('shipments.table.couriers')
@else
    @if(in_array('returned',$applied['types'])))
        @include('shipments.table.returned')
    @else
        @include('shipments.table.default')
    @endif
@endif